export type ManagementPerson = {
  id: string;
  slug: string;
  name: string;
  position: string;
  group: "GS" | "DGS" | "DIRECTOR";
  directorate?: string;
  photo: string;
  bio: string;
  email?: string;
  phone?: string;
};

const bioBase =
  "Dr. [Name] brings extensive experience in statistical leadership, policy advisory, and national development planning. Their work focuses on data quality, modernization of statistical systems, and strengthening the National Statistical System across sectors.";

export const MANAGEMENT: ManagementPerson[] = [
  {
    id: "gs",
    slug: "dr-alhassan-iddrisu",
    name: "Dr. Alhassan Iddrisu",
    position: "Government Statistician",
    group: "GS",
    directorate: "Office of the Government Statistician",
    photo: "/images/management/gs.jpg",
    bio: bioBase.replace("[Name]", "Alhassan Iddrisu"),
    email: "gs@statsghana.gov.gh",
  },
  {
    id: "dgs",
    slug: "mr-omar-seidu-dgs",
    name: "Mr. Omar Seidu",
    position: "Deputy Government Statistician",
    group: "DGS",
    directorate: "Office of the Deputy Government Statistician",
    photo: "/images/management/omarseidu.jpeg",
    bio: bioBase.replace("[Name]", "Omar Seidu"),
    email: "dgs@statsghana.gov.gh",
  },
  {
    id: "director-13",
    slug: "mr-mark-abuabu-dadzie",
    name: "Mr. Mark Abuabu-Dadzie",
    position: "Director",
    group: "DIRECTOR",
    directorate: "Digital Services and Technology",
    photo: "/images/management/mark.jpg",
    bio: bioBase.replace("[Name]", "Mark Abuabu-Dadzie"),
  },
  {
    id: "director-10",
    slug: "mr-kwadwo-asante-mensah",
    name: "Mr. Kwadwo Asante Mensah",
    position: "Director",
    group: "DIRECTOR",
    directorate: "Administration",
    photo: "/images/management/kwadwoasante.jpg",
    bio: bioBase.replace("[Name]", "Kwadwo Asante Mensah"),
  },
  {
    id: "director-7",
    slug: "mrs-abena-osei-akoto",
    name: "Mrs. Abena Osei-Akoto",
    position: "Director",
    group: "DIRECTOR",
    directorate: "Survey and Census Organisation",
    photo: "/images/management/abenaosei.jpg",
    bio: bioBase.replace("[Name]", "Abena Osei-Akoto"),
  },
  {
    id: "director-9",
    slug: "mr-david-bessah",
    name: "Mr. David Bessah",
    position: "Ag. Director",
    group: "DIRECTOR",
    directorate: "Communication and Dissemination",
    photo: "/images/management/bessah.jpg",
    bio: bioBase.replace("[Name]", "David Bessah"),
  },
  {
    id: "director-14",
    slug: "mr-emmanuel-cobbinah",
    name: "Mr. Emmanuel Cobbinah",
    position: "Director",
    group: "DIRECTOR",
    directorate: "Internal and External Cooperation",
    photo: "/images/management/cobinnah.jpg",
    bio: bioBase.replace("[Name]", "Emmanuel Cobbinah"),
  },
  {
    id: "director-1",
    slug: "dr-johnson-owusu-kagya",
    name: "Dr. Johnson Owusu Kagya",
    position: "Director",
    group: "DIRECTOR",
    directorate: "Business, Industry and Trade (BIT)",
    photo: "/images/placeholder-person.png",
    bio: bioBase.replace("[Name]", "Johnson Owusu Kagya"),
  },
  {
    id: "director-2",
    slug: "mr-francis-bright-mensah",
    name: "Mr Francis Bright Mensah",
    position: "Director",
    group: "DIRECTOR",
    directorate: "Economy",
    photo: "/images/placeholder-person.png",
    bio: bioBase.replace("[Name]", "Francis Bright Mensah"),
  },
  {
    id: "director-3",
    slug: "dr-lucy-twumwaa",
    name: "Dr. Lucy Twumwaa",
    position: "Ag.Director",
    group: "DIRECTOR",
    directorate: "Methods and Standards",
    photo: "/images/placeholder-person.png",
    bio: bioBase.replace("[Name]", "Lucy Twumwaa"),
  },
  {
    id: "director-4",
    slug: "mrs-samilia-enyamah-mintah",
    name: "Mrs Samilia Enyamah Mintah",
    position: "Ag. Director",
    group: "DIRECTOR",
    directorate: "Research and Data Science",
    photo: "/images/placeholder-person.png",
    bio: bioBase.replace("[Name]", "Samilia Enyamah Mintah"),
  },
  {
    id: "director-5",
    slug: "mr-omar-seidu",
    name: "Mr. Omar Seidu",
    position: "Director",
    group: "DIRECTOR",
    directorate: "Social",
    photo: "/images/placeholder-person.png",
    bio: bioBase.replace("[Name]", "Omar Seidu"),
  },
  {
    id: "director-6",
    slug: "mr-godwin-odei-gyebi",
    name: "Mr. Godwin Odei Gyebi",
    position: "Director",
    group: "DIRECTOR",
    directorate: "Demography",
    photo: "/images/placeholder-person.png",
    bio: bioBase.replace("[Name]", "Godwin Odei Gyebi"),
  },
  {
    id: "director-8",
    slug: "dr-abekah-ansah",
    name: "Dr. Abekah Ansah",
    position: "Ag. Director",
    group: "DIRECTOR",
    directorate: "Programme Monitoring and Evaluation",
    photo: "/images/placeholder-person.png",
    bio: bioBase.replace("[Name]", "Abekah Ansah"),
  },
  {
    id: "director-11",
    slug: "mr-isaac-odoom",
    name: "Mr. Isaac Odoom",
    position: "Ag.Director",
    group: "DIRECTOR",
    directorate: "Human Resource",
    photo: "/images/placeholder-person.png",
    bio: bioBase.replace("[Name]", "Isaac Odoom"),
  },
  {
    id: "director-12",
    slug: "mr-afful",
    name: "Mr. Afful",
    position: "Director",
    group: "DIRECTOR",
    directorate: "Finance",
    photo: "/images/placeholder-person.png",
    bio: bioBase.replace("[Name]", "Afful"),
  },
  {
    id: "director-15",
    slug: "mr-david-asare",
    name: "Mr. David Asare",
    position: "Head",
    group: "DIRECTOR",
    directorate: "Internal Audit",
    photo: "/images/placeholder-person.png",
    bio: bioBase.replace("[Name]", "David Asare"),
  },
];
